### ISSUE TITLE
Ogre update

### ISSUE THREAD

**Issue by Kelldoran** [BitPsycho/BS_KOW_Vanguard#30]
Ogres have had new units and stats since september and still haven't gotten them added to the roster.

**Comment by BitPsycho** [comment]
Adding the ogre warband was indeed on my to do list for Q4 of 2020.  

Mantic requires me to wait 3 months after the official release date.

I have been in contact with Mantic several times now to get the data but unfortunately they are not willing to share the data as they require easyarmy.com to be updated first and apparently some delay was there.  Since then they did not respond to any further email requests.

I will ask them again.

**Comment by BitPsycho** [comment]
Mantic finally approved.

Implemented with upcoming release 1.10.

**Comment by Kelldoran** [comment]
So glad to see it and get theory crafting! Only missed thing I saw is that the Brawler is missing its crushing 1On Jan 6, 2021 11:14 AM, BitPsycho <notifications@github.com> wrote:
Mantic finally approved.
Implemented with upcoming release 1.10.

**Comment by BitPsycho** [comment]
Thanks for reporting.  Release 1.10.1 with the fix for the brawler is underway.

**Comment by Kelldoran** [comment]
Glad to help. If you need to know any of the stuff that got added/updated for 3rd edition KOW I have all the changes for the most part.On Jan 13, 2021 4:03 AM, BitPsycho <notifications@github.com> wrote:
Thanks for reporting.  Release 1.10.1 with the fix for the brawler is underway.
